/**
 * Barcode parsing.
 *
 * Today every scan yields a plain GTIN — the 1D symbologies carry nothing but
 * the product identifier. GS1 Sunrise 2027 moves packaging to 2D codes
 * (DataMatrix / QR) that additionally carry the batch and the *actual* expiry
 * date, which is the one thing our estimator has to guess at right now.
 *
 * So `parseScan` returns a shape with an `expiresAt` slot that is always null
 * for 1D symbologies. When the 2D branch lands, only `parseScan` changes:
 * everything downstream already treats a known expiry date as optional.
 */

export type ScanKind =
  /** A real GTIN: same code for this product in every shop, every country. */
  | 'gtin'
  /**
   * In-store label (prefix 2): generated by the shop's scale for something
   * weighed or cut to order. Encodes a price or a weight and means nothing
   * outside that shop, so there is no point asking Open Food Facts about it.
   */
  | 'in_store'
  /** Not a retail barcode we know how to read. */
  | 'unknown'

export type ParsedScan = {
  kind: ScanKind
  /** Normalised digits. For `unknown`, whatever was scanned. */
  code: string
  /** True when the GS1 check digit matches. */
  validChecksum: boolean
  /**
   * Expiry date carried by the symbol itself. Always null until we parse
   * GS1 2D codes (application identifier 17, format YYMMDD).
   */
  expiresAt: null
}

/** GS1 modulo-10 check digit, valid for EAN-8, UPC-A and EAN-13 alike. */
function computeCheckDigit(digits: string): number {
  const body = digits.slice(0, -1)
  let sum = 0
  let weight = 3

  for (let i = body.length - 1; i >= 0; i--) {
    sum += Number(body[i]) * weight
    weight = weight === 3 ? 1 : 3
  }

  return (10 - (sum % 10)) % 10
}

export function hasValidChecksum(code: string): boolean {
  if (!/^\d{8}$|^\d{12,14}$/.test(code)) return false
  return computeCheckDigit(code) === Number(code[code.length - 1])
}

/**
 * UPC-A is the 12-digit US form of the same GTIN. Left-padding to 13 keeps a
 * single key in the database and matches what Open Food Facts stores.
 */
export function normalize(raw: string): string {
  const digits = raw.replace(/\D/g, '')
  return digits.length === 12 ? `0${digits}` : digits
}

export function parseScan(raw: string): ParsedScan {
  const code = normalize(raw)

  if (!/^\d{8}$|^\d{13,14}$/.test(code)) {
    return { kind: 'unknown', code: raw, validChecksum: false, expiresAt: null }
  }

  const validChecksum = hasValidChecksum(code)

  /**
   * Prefix 2 is reserved for in-store use. On a 13-digit code the padded
   * UPC-A form puts it in second position, so check both.
   */
  const inStore = code.length === 13 ? code[0] === '2' || code.startsWith('02') : code[0] === '2'

  return {
    kind: inStore ? 'in_store' : 'gtin',
    code,
    validChecksum,
    expiresAt: null,
  }
}
